"""empty message

Revision ID: 2e195e0e79ad
Revises: d3cad0ffc28
Create Date: 2014-08-07 16:55:28.708194

"""

# revision identifiers, used by Alembic.
revision = '2e195e0e79ad'
down_revision = 'd3cad0ffc28'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
