"""empty message

Revision ID: 436906ce57ec
Revises: c92b8b446f2
Create Date: 2014-08-07 20:36:36.224811

"""

# revision identifiers, used by Alembic.
revision = '436906ce57ec'
down_revision = 'c92b8b446f2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
