"""empty message

Revision ID: c92b8b446f2
Revises: 2e195e0e79ad
Create Date: 2014-08-07 19:43:02.746993

"""

# revision identifiers, used by Alembic.
revision = 'c92b8b446f2'
down_revision = '2e195e0e79ad'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
